 
            var base_url = 'https://dashboard.subiz.com/';
var resource_url = "https://dashboard.subiz.com/public/";
var resource_css = "https://css-dashboard.subiz.com/";
var resource_image = "https://agent-data.subiz.com/";
var socket_iso =  "https://ws-dashboard-lb-1.subiz.com/";
var socket_iso_1 =  "https://ws-dashboard-lb-2.subiz.com";
var socket_iso_2 =  "https://ws-dashboard-lb-3.subiz.com";
var socket_iso_3 =  "";
var check_ready = false;
var css_ready = false;
var id_package = "2";
var ready_play_message = false;
var ready_play_request = false;

var php_current_time = "2016-11-19 22:54:55";
var token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo1Mzg2OCwidXNlcm5hbWUiOiJkdW9uZ2N1b25nNzg5IiwidGltZSI6IjIwMTYtMTEtMTkgMTI6MzY6MDQifQ.xAPokxmFfaE8TH4AJ1yW3p7rEfyIh8IzzrMA_igtHDI';
 
 
            var js_lang = {
                the_system_is_currently_being_upgraded: "Hệ thống đang được tiến hành nâng cấp",
                your_browser_will_automatically_refresh_after: "Trình duyệt của bạn sẽ tự động refresh sau:",
                seconds: "giây",
                notification_not_allow: "Subiz cần bạn cho phép để bật chức năng thông báo.",
                notification_not_support: "Thông báo ngoài màn hình nền hiện tại chưa được hỗ trợ cho trình duyệt của bạn.",
                notification_denied: "Thông báo bị từ chối. (Thay đổi quyền cho phép thông báo trong phần cài đặt trong trình duyệt)",
                login_error_msg: "Đăng nhập bị trùng lặp. <a href=\'https://dashboard.subiz.com/login/logout\'>Đăng nhập lại</a>",
                connecting_error_attemping_reconnect: "Kết nối gián đoạn, đang thực hiện lại...",
                disconnected_try_now: "Kết nối bị gián đoạn, <a href=\'javascript:void(0);\' id=\'connect_trynow\'>thử lại</a>.",
                connecting_error: "Lỗi kết nối, <a href=\'javascript:void(0);\' id=\'connect_trynow\'>thử lại</a>.",
                disconnected_attemping_to_connect: "Kết nối bị gián đoạn, đang thực hiện lại...",
                online_status: "Tôi đang online trên Subiz",
                type_here_and_hit_enter_to_enter_chat: "Gõ vào đây và enter để chat",
                start_typing_to_join_the_chat: "Gõ vào đây để bắt đầu cuộc chat",
                visitor_is_typing: "đang gõ...",
                visitor_label: "Nhãn",
                visitor_looking: "Đang xem",
                visitor_referred: "Referrer",
                attemping_reconnect: "Attemping reconnect...",
                select_action: "Chọn hành động",
                subscription_transfer_chat: "Chuyển chat",
                end_chat: "Kết thúc trò chuyện",
                ban_visitor: "Chặn visitor",
                double_click_edit: "Click hai lần ở đây để sửa đổi",
                information: "Thông tin",
                note: "Ghi chú",
                history_time_on_site: "Thời gian trên website",
                history_more: "Nhiều hơn",
                history_less: "Ít hơn",
                looking: "Đang xem",
                history_already: "Vừa xem :",
                to_minimize_this_chat: "Để thu nhỏ cuộc hội thoại, ấn nút thu nhỏ hoặc thoát ra ngoài cửa sổ chat",
                cancel: "Hủy bỏ",
                ban_visitors: "Chặn visitor",
                reason: "Lý do",
                also_ban_visitor_IP_adress: "Đồng thời chặn địa chỉ IP visitor",
                visitor_offline: "Visitor đã offline",
                no_visitor: "Bạn chưa có khách truy cập",
                no_request_chat: "Bạn chưa có yêu cầu chat",
                perform_test: "Xem trước tính năng chat trên ",
                type_and_chat: "Gõ và nhấn Enter để chat",
                signed_another_device: "Tài khoản của bạn đã được đăng nhập ở thiết bị khác, <a href=\'javascript:void(0);\' id=\'connect_trynow\'>thử lại</a>.",
                agent_blocked:"Thông báo!  Agent của bạn tạm thời không thể truy cập vào Dashboard. Bạn vui lòng quay lại trong 10 phút nữa. Cảm ơn !",
                f5_to_continue: "Thời gian kết nối đến Dashboard quá lâu, Nhấn Ctrl+F5 để thử lại hoặc <a href=\"http://subiz.com/help/test\" target=\"_blank\">vào đây</a> để xác định nguyên nhân.",
                cannot_connect_socket: "Nhấn F5 để login lại. Nếu sau khi login lại bạn vẫn thấy thông báo này thì vui lòng liên hệ với chúng tôi.",
                check_mail: "Vui lòng check mail để kích hoạt tài khoản.",
                sure:"Bạn có thực sự muốn xóa bản ghi này?",
                use_cus_survey:"Bạn đang chọn Auto detect ngôn ngữ. Hãy chọn một ngôn ngữ cụ thể để có thể chỉnh sửa form khảo sát.",
                today:"Hôm nay",
                yesterday:"Hôm qua",
                two_day_ago:"2 Ngày trước",
                three_day_ago:"3 Ngày trước",
                new:"Mới",
                return:"Quay lại",
                find:"Tìm kiếm",
                no_permission:"Bạn không có quyền truy cập Lịch sử này",
                vistior_endchat:"Khách truy cập kết thúc chat",
                system_end_chat:"Cuộc chat đã kết thúc.",
                mes_end_chat:"kết thúc chat",
                no_permission_chat:"Bạn không có quyền xem cuộc Chat này.<br /> Visitor đang chat với ",
                no_permission_report:"Bạn không có quyền xem thống kê này",
                setting_close: "Đóng",
                setting_edit: "Sửa",
                perm_close: "Đóng",
                perm_edit: "Sửa",
                firefox_denied:'Trình duyệt của bạn đang vô hiệu tính năng hiển thị thông báo trên màn hình. <b>Tool > Page Info > Permissions</b> ở Firefox và chọn \"Allow\" trong mục \"Show Notifications”. Sau đó tải lại trang.',
                chrome_denied:'Trình duyệt của bạn đang vô hiệu tính năng hiển thị thông báo trên màn hình. <b>Settings > Show advanced settings > Content settings</b> ở Chrome và chọn \"Allow all sites to show desktop notifications\". Sau đó click vào nút \"Manager exceptions...\" nếu trang https://dashboard.subiz.com đang bị block bạn cần xóa dòng đó đi,tải lại trang.',
                safari_denied:'Trình duyệt của bạn đang vô hiệu tính năng hiển thị thông báo trên màn hình.Choose Safari > Preferences, click Notifications, và chọn  Allow hoặc Deny đối với những website mà bạn muốn thay đổi quyền hiển thị thông báo.',
                chat_request_title:'Subiz live chat',
                chat_request_body:'Bạn có một yêu cầu chat mới',
                new_message_title:'Subiz live chat',
                new_message_body:'Bạn có tin nhắn mới',
                new_visitor_title:'Subiz live chat',
                new_visitor_body:'Có khách lần đầu tiên vào website bạn',
                return_visitor_title:'Subiz live chat',
                return_visitor_body:'Có khách cũ vừa quay lại website của bạn',
                noti_enabled:'Thông báo màn hình đã được bật',
                vistor_active_visitors:'Active Visitors',
                vistor_idle_visitors:'Idle Visitors',
                vistor_request_chats:'Yêu cầu Chat',
                history_disable : 'Chức năng đang được bảo trì, Subiz xin lỗi bạn về sự bất tiện này. Vui lòng <a href=\"http://subiz.com/contact.html\" target=\"_blank\" > liên hệ với chúng tôi </a> để được hỗ trợ lấy dữ liệu.',
                message_limit_60_chat : 'Tài khoản của bạn đã sử dụng hết số lượng cuộc chat cho phép của gói miễn phí. Mời bạn <a href=\"http://subiz.com/landingpage/faqs/faqs.html?faq=66\" target=\"_blank\" >liên hệ với chúng tôi</a> để được hỗ trợ',
                add_a_tag : 'Gán tag',
                tag_setting : 'Cài đặt tag',
                delete: 'Xóa',
                added_this_tag_on: 'đã thêm tag này vào',
                file_send:"Gửi",
                file_cancel:"Hủy",
                file_can_upload:"File được gửi",
                file_cannot_upload:"Những file này không được hỗ trợ",
                file_upload_failed:"Tải file có lỗi",
                message_too_long:"Tin nhắn quá dài, vui lòng rút gọn và gửi lại.",
                server_error:"Không thể kết nối Dashboard, vui lòng <a href=\"http://subiz.com/help/test\" target=\"_blank\"> vào đây </a> để kiểm tra nguyên nhân và liên hệ với Subiz.",
                change_status_away:"Bạn đã chuyển trạng thái sang Away",
                change_status_avai: "Bạn đã chuyển trạng thái sang Available",
                day_ago: "ngày trước",
                days_ago: "ngày trước",
                hour_ago: "giờ trước",
                hours_ago: "giờ trước",
                minute_ago: "phút trước",
                minutes_ago: "phút trước",
                few_second_ago: "vài giây trước",
                no_notification: "Bạn không có thông báo nào",
                app_need_reinstall : "Ứng dụng vừa được cập nhật, bạn nên tắt và mở lại để hoàn tất việc cập nhật."
            };
var canned_js = {
    status: "Trạng thái",
    function: "Tác vụ",
    shortcut: "Viết tắt",
    message:"Tin nhắn",
    canned_responses: "Thư viện câu trả lời",
    create_canned_responses: "Tạo câu trả lời mẫu",
    enable: "On",
    disable: "Off",
    package_allows: "Package allows",
    delete: "Xóa",
    edit: "Sửa",
    save_change: "Lưu thay đổi",
    cancel: "Hủy bỏ",
    close: "Đóng",
    history_find_now: "Tìm kiếm ngay",
    message_require:"Tin nhắn không được trống.",
    export:"Xuất",
    import:"Nhập",
    history_file_type:"Định dạng file",
    history_submit:"Xuất",
    history_cancel:"Hủy bỏ",
    upload_success:"Import thành công.",
    upload_invalid:"Định dạng tài liệu không đúng",
    search:"Tìm kiếm",
    message_length:"Nội dung tin nhắn không vượt quá 250 kí tự",
    keyword:"Từ khóa",
    canned_not_use:"Chức năng này không có sẵn cho tài khoản của bạn. Vui lòng nâng cấp tài khoản lên gói cơ bản hoặc nâng cao để sử dụng chức năng này.",
    share_for_agent:"Chia sẻ",

};
var history_js = {
    history_export: "Xuất",
    history_date: "Ngày",
    history_agent: "Agent",
    history_department: "Bộ phận",
    history_rating: "Đánh giá",
    history_rated_chat: "Được đánh giá",
    history_not_rated: "Không được đánh giá",
    history_rated_bad: "Đánh giá không tốt",
    history_rated_good: "Đánh giá tốt",
    history_type: "Loại",
    history_tag: "Tag",
    history_new_visitor: "Visitor mới",
    history_return_visitor: "Visitor quay lại",
    history_filter: "Lọc cuộc chat theo:",
    history_search: "Tìm kiếm visitor",
    history_transcript: "TRANSCRIPT",
    history_visitor_info: "Thông tin ",
    history_visitor_notes: "Ghi chú",
    history_close: "Đóng",
    history_error_date:"Vui lòng kiểm tra lại thời gian, khoảng thời gian cho phép không vượt quá 30 ngày!",
    history_email_empty: "Email không được bỏ trống",
    add_a_tag : 'Gán tag',
};
var agent_js = {
    agents: "Agent",
    department: "Bộ phận",
    email: "Email",
    user_name: "Tên đăng nhập",
    member_of_department: "Nhân viên của Bộ phận",
    last_loged: "Lần đăng nhập cuối",
    type: "Loại",
    last_7_days: "7 ngày vừa qua",
    edit: "Sửa",
    add_more_agents: "Thêm agent",
    search_agents: "Tìm kiếm agent",
    select_timezone: "Chọn múi giờ",
    change_password: "Thay đổi mật khẩu",
    change_avatar: "Thay ảnh đại diện",
    name: "Tên",
    password: "Mật khẩu",
    retype_password: "Gõ lại mật khẩu",
    job_title: "Vị trí công việc",
    timezone: "Múi giờ",
    dashboard_lang: "Ngôn ngữ Dashboard",
    english: "English",
    vietnamese: "Tiếng Việt",
    normal: "Normal",
    administrator: "Administrator",
    status: "Trạng thái",
    save_change: "Lưu thay đổi",
    your_account_has_been: "Tài khoản của bạn đã sử dụng số lượng Agent tối đa cho phép. Xin vui lòng <a href=\"https://dashboard.subiz.com/subscription/index\" target=\"_blank\">nâng cấp tài khoản</a>!",
    add_more_department: "Thêm Bộ phận",
    add_department: "Thêm Bộ phận",
    department_name: "Tên bộ phận",
    search_depat: "Tìm kiếm Bộ phận",
    available: "Available",
    away: "Away",
    offline: "Offline",
    cancel: "Hủy bỏ",
    avatar_max_size: "Dung lượng tối đa 200kb",
    msg_agent_username_condition : "Tên đăng nhập chỉ bao gồm chữ thường và số, độ dài từ 6 kí tự trở lên và bắt đầu bằng chữ!",
};
var js_lang_chat_template = {
    add_a_tag : 'Gán tag',
};
var ls_lang_webhook = {
    webhook_description_reset_apikey: "Sử dụng API key này để xác nhận khi truy cập hệ thống API public của Subiz.",
    webhook_descripttion: "Webhook cho phép bạn xây dựng hoặc thiết lập tích hợp để nhận những sự kiện cụ thể từ Subiz.com.",
    webhook_reset_api: "Thiết lập lại API key  ",
    webhook_title_delete: "Bạn chắc chắn muốn xóa webhook này?",
    webhook_title_note_delete: "Bạn không thể quay lại ở bước này.",
    webhook_error_url: "URL không khả dụng",
    webhook_error_url_null: "Vui lòng điền webhook URL của bạn",
    webhook_error_key: "Vui lòng điền Khóa bảo mật của bạn",
    webhook_error_null: "Không có lỗi mới",
    webhook_error_latest: "Dưới đây là thông tin về 20 lỗi mới nhất",
    webhook_required_field: "Các trường bắt buộc",
    webhook_name_setting: "Cài đặt webhook",
    webhook_log_error: "Ghi lại lỗi",
    webhook_help_link: "Trợ giúp",
    webhook_name_event: "Sự kiện",
    webhook_error_time: "Thời gian",
    webhook_error_detail: "Cụ thể",
    webhook_view_detail: "Xem chi tiết",
    webhook_error_response: "Không có phản hồi",
    webhook_secret_key: "Khóa bảo mật",
    webhook_save: "Lưu",
    webhook_edit: "Sửa",
    webhook_delete: "Xóa",
    webhook_learn_more:  "Đọc thêm",
    webhook_secret_key_description: "Cung cấp mã bí mật là cách tốt nhất để bảo mật dữ liệu của bạn. ",
    webhook_version_doc: "1.0.0",
} 